
Neos:
  Demo:
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Claudio.Render/Private/Form/'
    presets:
      bootstrap:
        title: 'Twitter bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Claudio.Render/Private/Templates/ContactForm/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: print
          title: 'Claudio.Render:Main:editPreviewModes.print'
          position: 200
      translation:
        autoInclude:
          Claudio.Render:
            - Main
            - 'NodeTypes/*'
  ContentRepository:
    contentDimensions:
      language:
        label: 'Claudio.Render:Main:contentDimensions.language'
        icon: icon-language
        default: de_CH
        defaultPreset: de_CH
        presets:
          de_CH:
            label: 'Deutsch (Ch)'
            values:
              - de_CH
            uriSegment: de
